export { authService } from './auth.service'
export { catalogService } from './catalog.service'
export { contactService } from './contact.service'
export { eventsService } from './events.service'
export { ordersService } from './orders.service'
export { paymentsService } from './payments.service'
